version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./app:/laravel-aws
      - ./.docker/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./.docker/php
    volumes:
      - ./app:/laravel-aws
    working_dir: /laravel-aws
    links:
      - rabbitmq
      - db
      - localstack

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.docker/rabbitmq/data:/var/lib/rabbitmq
      - ./.docker/rabbitmq/log:/var/log/rabbitmq

  db:
    image: mysql:latest
    env_file:
      - ./.env.template
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  localstack:
    image: localstack/localstack:latest
    environment:
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3
      - EAGER_SERVICE_LOADING=1
    ports:
      - "4566-4583:4566-4583"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/localstack/data:/tmp/localstack
