version: "3.7"

services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./app:/laravel-aws
      - ./.docker/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./.docker/php
    volumes:
      - ./app:/laravel-aws
    working_dir: /laravel-aws
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.docker/rabbitmq/data:/var/lib/rabbitmq
      - ./.docker/rabbitmq/log:/var/log/rabbitmq
